### ISSUE TITLE
there is no apk

### ISSUE THREAD

**Issue by elliot-holley** [antrromet/virus#2]
where is the apk

**Comment by l4km47** [comment]
Lol. dude This is a source code

**Comment by ZechBron** [comment]
@elliot-holley   and @l4km47 l4km47

You can get the source code and make it an apk. Like I did.

**Comment by ghost** [comment]
How to convert source code into apk

**Comment by elliot-holley** [comment]
i wasnt pariticularly clever back then was i

**Comment by elliot-holley** [comment]
this repo isnt maintained anymore, so i suppose ill close this down.
